// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API support and feedback",
            "url": "-",
            "email": "2195058149@qq.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/wensboy/sss/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/check": {
            "get": {
                "description": "健康检查 - Check端点，用于综合检查服务各组件状态，返回 \"check\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Check",
                "responses": {
                    "200": {
                        "description": "成功响应，code=0, msg=\\\"check\\\", data=nil",
                        "schema": {
                            "$ref": "#/definitions/model.RestResponse"
                        }
                    }
                }
            }
        },
        "/healthy": {
            "get": {
                "description": "健康检查 - Healthy端点，用于检测服务是否处于健康状态，返回 \"healthy\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Healthy",
                "responses": {
                    "200": {
                        "description": "成功响应，code=0, msg=\\\"healthy\\\", data=nil",
                        "schema": {
                            "$ref": "#/definitions/model.RestResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "健康检查 - Ping端点，用于检测服务是否可达，返回 \"pong\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "成功响应，code=0, msg=\\\"pong\\\", data=nil",
                        "schema": {
                            "$ref": "#/definitions/model.RestResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.RestResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "SSS API Definition",
	Description:      "sss is a simple pre-built service repository that contains endpoint definitions for commonly integrable services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
