basePath: /api
definitions:
  model.RestResponse:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: 2195058149@qq.com
    name: API support and feedback
    url: '-'
  description: sss is a simple pre-built service repository that contains endpoint
    definitions for commonly integrable services.
  license:
    name: MIT
    url: https://github.com/wensboy/sss/blob/main/LICENSE
  title: SSS API Definition
  version: "1.0"
paths:
  /check:
    get:
      consumes:
      - application/json
      description: 健康检查 - Check端点，用于综合检查服务各组件状态，返回 "check"
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应，code=0, msg=\"check\", data=nil
          schema:
            $ref: '#/definitions/model.RestResponse'
      summary: Check
      tags:
      - health
  /healthy:
    get:
      consumes:
      - application/json
      description: 健康检查 - Healthy端点，用于检测服务是否处于健康状态，返回 "healthy"
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应，code=0, msg=\"healthy\", data=nil
          schema:
            $ref: '#/definitions/model.RestResponse'
      summary: Healthy
      tags:
      - health
  /ping:
    get:
      consumes:
      - application/json
      description: 健康检查 - Ping端点，用于检测服务是否可达，返回 "pong"
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应，code=0, msg=\"pong\", data=nil
          schema:
            $ref: '#/definitions/model.RestResponse'
      summary: Ping
      tags:
      - health
swagger: "2.0"
